#!/bin/bash
#VALUE_SIZE_POWER_RANGE="8 11" CONN_CLI_COUNT_POWER_RANGE="8 8" PG_KV_TYPE_LIST="lbr_now_nifs" PG_CMP_WAL_LIST="lz4" RATIO_LIST="1/128" ./pg-thunderdome.sh -n
#PG_CMP_ORIOLE_LIST="1" VALUE_SIZE_POWER_RANGE="8 11" PG_KV_TYPE_LIST="lbr_now_nifs" PG_CMP_WAL_LIST="lz4" RATIO_LIST="128/1" CONN_CLI_COUNT_POWER_RANGE="11 11" ./pg-thunderdome.sh -n
VALUE_SIZE_POWER_RANGE="8 11" CONN_CLI_COUNT_POWER_RANGE="8 8" PG_KV_TYPE_LIST="lbr_now_nifs" PG_CMP_WAL_LIST="lz4" RATIO_LIST="1/128" ./pg-thunderdome.sh -o
VALUE_SIZE_POWER_RANGE="8 11" PG_KV_TYPE_LIST="lbr_now_nifs" PG_CMP_WAL_LIST="lz4" RATIO_LIST="128/1" CONN_CLI_COUNT_POWER_RANGE="11 11" ./pg-thunderdome.sh -o
