#!/bin/bash

#VALUE_SIZE_POWER_RANGE="8 11" CONN_CLI_COUNT_POWER_RANGE="5 9" RATIO_LIST="1/128" ./pg-thunderdome.sh
VALUE_SIZE_POWER_RANGE="9 11" CONN_CLI_COUNT_POWER_RANGE="11 11" RATIO_LIST="128/1" ./pg-thunderdome.sh
