include:
  - ../pgetcd_compose.yaml

services:
  # --- The Database ---
  pgdb:
    shm_size: 4gb
    image: orioledb/orioledb:beta16-pg18
    container_name: ${DB_NAME:-oriole18}
    configs:
      - source: pg_config
        target: /etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      # Maps the named volume to the container path
      - socket-dir:/var/run/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - etcd_bridge
configs:
  pg_config:
    content: |+
      data_directory = '/var/lib/postgresql/data'
      hba_file = '/var/lib/postgresql/data/pg_hba.conf'
      listen_addresses = '*'
      shared_preload_libraries = 'orioledb'
      default_table_access_method = 'orioledb'
      max_wal_size = 8GB
      min_wal_size = 1GB
      shared_buffers = 128MB
      work_mem = 512MB
      checkpoint_timeout = 30s
      max_connections = 128
      wal_compression = ${CMP_WAL:-off}
      orioledb.checkpoint_completion_ratio = 1.0
      orioledb.main_buffers = 4GB
      orioledb.undo_buffers = 256MB
      orioledb.free_tree_buffers = 256MB
      orioledb.table_description_compress = on
      orioledb.default_compress = ${CMP_DEF:--1}
      orioledb.default_primary_compress = ${CMP_PRI:--1}
      orioledb.default_toast_compress = ${CMP_TST:--1}
